# Generated by Django 4.2.7 on 2023-11-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_remove_car_color_car_transmission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='child_seat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_type',
            field=models.CharField(choices=[('young', 'Young'), ('standart', 'Standart'), ('senior', 'Senior')], default='standart', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='rules_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='surname',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electic', 'Electric')], default='petrol', max_length=10),
        ),
    ]
