# Generated by Django 4.2.7 on 2023-11-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_booking_child_seat_booking_insurance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='insurance_type',
            field=models.CharField(choices=[('Young', 'Young'), ('Standart', 'Standart'), ('Senior', 'Senior')], default='standart', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electic', 'Electric')], default='petrol', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='manual', max_length=10),
        ),
    ]
