# Generated by Django 4.2.7 on 2023-11-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0004_alter_booking_insurance_type_alter_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='insurance_type',
            field=models.CharField(choices=[('young', 'Young'), ('standart', 'Standart'), ('senior', 'Senior')], default='standart', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electic', 'Electric')], default='petrol', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=10),
        ),
    ]
