# Generated by Django 4.2.7 on 2023-11-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0005_alter_booking_insurance_type_alter_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='insurance_type',
            field=models.CharField(choices=[('young', 'Young (+50€)'), ('standart', 'Standart (+40€)'), ('senior', 'Senior (+60€)')], default='standart', max_length=10),
        ),
    ]
