# Generated by Django 4.2.7 on 2023-11-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0007_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='insurance_type',
            field=models.CharField(choices=[('young', 'Young (+50€)'), ('standard', 'Standard (+40€)'), ('senior', 'Senior (+60€)')], default='standart', max_length=10),
        ),
    ]
