# Generated by Django 4.2.7 on 2023-11-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0008_alter_booking_insurance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='insurance_type',
            field=models.CharField(choices=[('young', 'Young (+50€)'), ('standard', 'Standard (+40€)'), ('senior', 'Senior (+60€)')], default='standard', max_length=10),
        ),
    ]
